<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="studyPlan" nsURI="platform:/plugin/tdt4250.studyPlan.model/model/studyPlan.ecore"
    nsPrefix="studyPlan">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/acceleo/query/1.0"/>
    <details key="settingDelegates" value="http://www.eclipse.org/acceleo/query/1.0"/>
    <details key="invocationDelegates" value="http://www.eclipse.org/acceleo/query/1.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="#//CourseCode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credit" eType="#//Credit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="#//level"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programmeCourse" upperBound="-1"
        eType="#//CourseInProgram" containment="true" eOpposite="#//CourseInProgram/course"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StudyPlan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="programmes" upperBound="-1"
        eType="#//Programme" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Programme">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programmeStart" upperBound="-1"
        eType="#//ProgrammeStart" containment="true" eOpposite="#//ProgrammeStart/programme"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CourseGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//CourseInProgram"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="courseType" eType="#//courseType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CourseInProgram">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semester" lowerBound="1"
        eType="#//semesterType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="course" lowerBound="1"
        eType="#//Course" eOpposite="#//Course/programmeCourse"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
        <details key="derivation" value="self.course.name + ' - ' + self.semester.toString() + ' ' + self.year"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProgrammeStart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programme" lowerBound="1"
        eType="#//Programme" eOpposite="#//Programme/programmeStart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programmeLevel" lowerBound="1"
        eType="#//ProgrammeLevel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProgrammeLevel">
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="springContainsOnlySpringCourses" value="if self.springSemester &lt;> null then not self.springSemester.courses.semester.toString()->exists(name | name &lt;> 'Spring') else true endif"/>
      <details key="fallContainsOnlyFallCourses" value="if self.fallSemester &lt;> null then not self.fallSemester.courses.semester.toString()->exists(name | name &lt;> 'Fall') else true endif"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="springSemester" eType="#//Semester"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fallSemester" eType="#//Semester"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextProgrammeLevel" upperBound="-1"
        eType="#//ProgrammeLevel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="#//level"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semester">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="min30Credits"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="min30Credits" value="self.courses.course.credit->sum() = 30.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//CourseInProgram"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
        <details key="derivation" value="if self.eContainmentFeature() &lt;> null and self.eContainmentFeature().name = 'fallSemester' then 'Fall' else 'Spring' endif"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseGroup" eType="#//CourseGroup"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="CourseCode" instanceClassName="java.lang.String">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="pattern" value="\p{L}+\d+"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="semesterType">
    <eLiterals name="Fall"/>
    <eLiterals name="Spring" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="level">
    <eLiterals name="Level1"/>
    <eLiterals name="Level2" value="1"/>
    <eLiterals name="Level3" value="2"/>
    <eLiterals name="Level4" value="3"/>
    <eLiterals name="Level5" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="courseType">
    <eLiterals name="Mandatory"/>
    <eLiterals name="Elective" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Credit" instanceClassName="float">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="minExclusive" value="0.0"/>
      <details key="maxInclusive" value="10.0"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
